FROM node:22-slim AS builder

ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID

ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npx vite build

FROM node:22-slim AS runner

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY --from=builder /app/dist ./dist
COPY server ./server
COPY shared ./shared
COPY types.ts ./types.ts

ENV NODE_ENV=production
ENV USE_VERTEX_AI=true
ENV PORT=8080

EXPOSE 8080
CMD ["npx", "tsx", "server/index.ts"]
